// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CheckPoint
IntegerVector CheckPoint(IntegerVector pos, IntegerVector start, IntegerVector end);
RcppExport SEXP _CheckOverlap_CheckPoint(SEXP posSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(CheckPoint(pos, start, end));
    return rcpp_result_gen;
END_RCPP
}
// CheckRange
IntegerVector CheckRange(IntegerVector pos, IntegerVector start, IntegerVector end);
RcppExport SEXP _CheckOverlap_CheckRange(SEXP posSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(CheckRange(pos, start, end));
    return rcpp_result_gen;
END_RCPP
}
// CheckMatch
DataFrame CheckMatch(IntegerVector pos, IntegerVector start, IntegerVector end);
RcppExport SEXP _CheckOverlap_CheckMatch(SEXP posSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(CheckMatch(pos, start, end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CheckOverlap_CheckPoint", (DL_FUNC) &_CheckOverlap_CheckPoint, 3},
    {"_CheckOverlap_CheckRange", (DL_FUNC) &_CheckOverlap_CheckRange, 3},
    {"_CheckOverlap_CheckMatch", (DL_FUNC) &_CheckOverlap_CheckMatch, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CheckOverlap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
