# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Check if points in segments
#'@description
#'To check if a number in a range. 
#'Return a vector of 0,1 if the the number 
#'in a range(1) or not (0).
#'@param pos a vector of numbers of points
#'@param start a vector of numbers of starting position
#'@param end a vector of numbers of ending position
#'@examples
#'aa <- c(2,4,6)
#'bb1 <- c(1,5,7)
#'bb2 <- c(3,8,10)
#'#too see if 2,4,6 in range 1-3,5-8,7-10
#'CheckPoint(aa,bb1,bb2)
#'@useDynLib CheckOverlap
#'@import Rcpp
#'@export
CheckPoint <- function(pos, start, end) {
    .Call('_CheckOverlap_CheckPoint', PACKAGE = 'CheckOverlap', pos, start, end)
}

#'@title Check if segments contain point
#'@description
#'To check if a range contains points. 
#'Return a vector of 0,1 
#'with 1 = contain points, 0 = not contain points.
#'@param pos a vector of numbers of points
#'@param start a vector of numbers of starting position
#'@param end a vector of numbers of ending position
#'@examples
#'aa <- c(2,4,6)
#'bb1 <- c(1,5,7)
#'bb2 <- c(3,8,10)
#'# to see if range 1-3,5-8, 7-8 contain 2,4,6
#'CheckRange(aa,bb1,bb2)
#'@useDynLib CheckOverlap
#'@import Rcpp
#'@export
CheckRange <- function(pos, start, end) {
    .Call('_CheckOverlap_CheckRange', PACKAGE = 'CheckOverlap', pos, start, end)
}

